service: marvel-ai-fetch-events
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - dynamodb:*
        Resource:
          - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/MarvelEvents
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource: arn:aws:s3:::dall-e-images-bucket/*

package: 
  individually: true

functions:

  fetchStories:
    handler: src/fetchStories.handler
    timeout: 6
          
  fetchUnused:
    handler: src/fetchUnused.handler
    timeout: 30

custom:
  dotenv:
    path: .env

resources:
  Resources:
    MarvelEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MarvelEvents
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
