service: marvel-ai-fetch-events
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript

custom:
  dotenv:
    path: .env

  eventsTable: ${env.EVENTS_TABLE}
  imagesbucket: ${env.BUCKET_NAME}
  # TOPICS
  generateImageTopicName: ${env.GENERATE_IMAGE_TOPIC_NAME}
  fetchImageTopicName: ${env.FETCH_IMAGE_TOPIC_NAME}
  updateDocumentTopicName: ${env.UPDATE_DOCUMENT_TOPIC_NAME}
  revalidatePathTopicName: ${env.REVALIDATE_PATH_TOPIC_NAME}

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - dynamodb:*
        Resource:
          - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self.custom.eventsTable}
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource: arn:aws:s3:::${self:custom.imagesbucket}/*
      - Effect: Allow
        Action:
          - sns:Publish
        Resource: !Ref ${self:custom.generateImageTopicName}

package: 
  individually: true

functions:
  fetchStories:
    handler: src/fetchStories.handler
    timeout: 20
          
  fetchUnused:
    handler: src/fetchUnused.handler
    timeout: 45
    events:
      - schedule:
          rate: cron(0 10 * * ? *)
          enabled: true
    environment:
      TOPIC_ARN: !Ref ${self:custom.generateImageTopicName}

  generateImage:
    handler: src/generateImage.handler
    events:
      - sns: ${self:custom.generateImageTopicName}
    environment:
      BUCKET: ${self:custom.imagesbucket}
      TOPIC_ARN: !Ref GenerateImageTopic

resources:
  Resources:
    GenerateImageTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.generateImageTopicName}

    FetchImageTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.fetchImageTopicName}

    UpdateDocumentTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.updateDocumentTopicName}

    RevalidatePathTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.revalidatePathTopicName}

    MarvelEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self.custom.eventsTable}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    CommentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Comments
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: N
          - AttributeName: commentId
            AttributeType: S
          - AttributeName: dateUpdated
            AttributeType: S
        KeySchema:
          - AttributeName: eventId
            KeyType: HASH
          - AttributeName: commentId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: EventDateIndex
            KeySchema:
              - AttributeName: eventId
                KeyType: HASH
              - AttributeName: dateUpdated
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    CaravarvelImagesbucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.imagesbucket}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          IgnorePublicAcls: false
          BlockPublicPolicy: false
          RestrictPublicBuckets: false

    CaravarvelImagesBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${self:custom.imagesbucket}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: "Statement1"
              Effect: "Allow"
              Principal: "*"
              Action: "s3:GetObject"
              Resource: !Sub "arn:aws:s3:::${self:custom.imagesbucket}/*"
