service: marvel-ai-fetch-events
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript

custom:
  dotenv:
    path: .env

  dallEImagesbucket: dall-e-images-bucket

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - dynamodb:*
        Resource:
          - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/MarvelEvents
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource: arn:aws:s3:::${self:custom.dallEImagesbucket}/*

package: 
  individually: true

functions:

  fetchStories:
    handler: src/fetchStories.handler
    timeout: 10
          
  fetchUnused:
    handler: src/fetchUnused.handler
    timeout: 30
    environment:
      BUCKET: ${self:custom.dallEImagesbucket}

resources:
  Resources:
    MarvelEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MarvelEvents
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    DallEImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.dallEImagesbucket}
