service: marvel-ai-fetch-events
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/MarvelEvents

functions:
  fetchStories:
    handler: src/fetchStories.handler
    events:
      - httpApi:
          path: /fetchMarvelEvents
          method: get

custom:
  dotenv:
    path: .env

resources:
  Resources:
    MarvelEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MarvelEvents
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
